record response {
    data: list<u8>,
}

enum io-format {
    binary,
    json,
    json-elements,
}

enum cardinality {
    no-result,
    at-most-one,
    one,
    many,
    at-least-one,
}

record error {
    code: u32,
    messages: list<string>,
    error: option<string>,
    headers: list<tuple<u16, list<u8>>>,
}

flags capabilities {
    modifications,
    session-config,
    transaction,
    ddl,
    persistent-config,
}

record compilation-flags {
    implicit-limit: option<u64>,
    implicit-typenames: bool,
    implicit-typeids: bool,
    allow-capabilities: capabilities,
    explicit-objectids: bool,
    io-format: io-format,
    expected-cardinality: cardinality,
}

record prepare-complete {
    capabilities: capabilities,
    cardinality: cardinality,
    input-typedesc-id: string,
    output-typedesc-id: string,
}

record data-description {
    proto: tuple<u16, u16>,
    result-cardinality: cardinality,
    input-typedesc-id: string,
    input-typedesc: list<u8>,
    output-typedesc-id: string,
    output-typedesc: list<u8>,
}
record data {
    chunks: list<list<u8>>,
}

resource query {
    describe-data: function() -> expected<data-description, error>
    execute: function(arguments: list<u8>) -> expected<data, error>
}

resource client {
    static connect: function() -> client
    transaction: function() -> expected<transaction, error>
    prepare: function(compilation-flags: compilation-flags, query: string)
        -> expected<tuple<query, prepare-complete>, error>
}

resource transaction {
    prepare: function(compilation-flags: compilation-flags, query: string)
        -> expected<tuple<query, prepare-complete>, error>
    commit: function() -> expected<unit, error>
    rollback: function() -> expected<unit, error>
}

