on:
  push:
    tags:
    - releases/edgedb-sdk-macros/v*

name: Release edgedb-sdk-macros

jobs:
  test_and_publish:
    uses: ./.github/workflows/publish.yaml
    with:
      crate: edgedb-sdk-macros
    secrets: inherit
