on:
  push:
    tags:
    - releases/edgedb-sdk/v*

name: Release edgedb-sdk

jobs:
  test_and_publish:
    uses: ./.github/workflows/publish.yml
    with:
      crate: edgedb-sdk
    secrets: inherit
